"""Connectors catalogue — third-party platforms that AML Agents integrates with.

Connectors don't just integrate — they POPULATE the STR drafting form. KYC data flows
into Subject, alerts into Triggering activity, screening hits into Sanctions panel, KYT
scores into Risk Index, etc.

Each connector has:
    name, category, description, homepage, status, integration_type, populates
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Connector:
    name: str
    category: str
    description: str
    homepage: str
    status: str = "On request"
    integration_type: str = "REST API"
    populates: tuple[str, ...] = ()


# Form sections this connector can populate when integrated.
POPULATES_SECTIONS = [
    'Subject (KYC, customer profile)',
    'Triggering activity (alerts, transactions)',
    'Risk Index score',
    'Sanctions / PEP screening',
    'Adverse media findings',
    'Supporting documents',
    'Counterparty intelligence',
    'Case post-back',
]


# Categories — primary collapsible groups in the UI
CATEGORIES = [
    'Identity, eKYC, KYB & Onboarding',
    'Behavioral & Device Intelligence',
    'AML Data, Screening & Regulatory Intelligence',
    'Enterprise FRAML & Decisioning Platforms',
    'Risk Orchestration',
    'Crypto AML & Blockchain Analytics',
    'Specialized Solutions',
]


STATUS_ORDER = {
    "Live": 0,
    "Beta": 1,
    "In development": 2,
    "Roadmap Q3 2026": 3,
    "Roadmap Q4 2026": 4,
    "Roadmap 2027": 5,
    "On request": 6,
}

STATUS_COLOURS = {
    "Live": "#10b981",
    "Beta": "#06b6d4",
    "In development": "#3b82f6",
    "Roadmap Q3 2026": "#8b5cf6",
    "Roadmap Q4 2026": "#a855f7",
    "Roadmap 2027": "#94a3b8",
    "On request": "#64748b",
}

ALL_STATUSES = list(STATUS_ORDER.keys())


CONNECTORS: list[Connector] = [
    Connector(
        'TrustSphere Risk Index',
        'Risk Orchestration',
        'Composite financial-crime risk score combining sanctions, PEP, adverse media, transaction-pattern, and beneficial-owner signals into a single 0–100 risk band. Powered by TrustSphere Partners.',
        'https://trustsphere.partners/risk-index',
        status='Live',
        integration_type='Native (in-app)',
        populates=('Risk Index score', 'Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'OpenSanctions',
        'AML Data, Screening & Regulatory Intelligence',
        "Open-data aggregated sanctions, PEP, and watchlist sources. Wired into the Subject section's screening button.",
        'https://www.opensanctions.org',
        status='Live',
        integration_type='REST API (/match/default)',
        populates=('Sanctions / PEP screening',),
    ),
    Connector(
        'Anthropic Claude API',
        'Enterprise FRAML & Decisioning Platforms',
        'Native PDF and image processing; primary engine for STR narrative drafting and uploaded-document analysis.',
        'https://docs.anthropic.com',
        status='Live',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Sumsub',
        'Identity, eKYC, KYB & Onboarding',
        'Comprehensive identity verification. Wiring webhook ingestion of KYC events for automatic Subject pre-fill.',
        'https://sumsub.com',
        status='In development',
        integration_type='Webhook + REST',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'ComplyAdvantage',
        'AML Data, Screening & Regulatory Intelligence',
        'Sanctions, PEP, and adverse-media screening with continuous monitoring. Replaces OpenSanctions for paid-tier customers.',
        'https://complyadvantage.com',
        status='In development',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Hawk AI',
        'Enterprise FRAML & Decisioning Platforms',
        'AI-native AML transaction monitoring; popular in EU fintech and digital banks. Connector to ingest alert payloads via webhook.',
        'https://hawk.ai',
        status='Roadmap Q3 2026',
        integration_type='Webhook (alert ingestion)',
        populates=('Triggering activity (alerts, transactions)', 'Risk Index score'),
    ),
    Connector(
        'Unit21',
        'Enterprise FRAML & Decisioning Platforms',
        'Modern TM and case management. Connector to pull alerts and post-back the drafted narrative to Unit21 case files.',
        'https://www.unit21.ai',
        status='Roadmap Q3 2026',
        integration_type='REST API (bidirectional)',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Sardine',
        'Behavioral & Device Intelligence',
        'Real-time fraud + AML monitoring; popular with crypto exchanges and neobanks.',
        'https://www.sardine.ai',
        status='Roadmap Q3 2026',
        integration_type='Webhook + REST',
        populates=('Triggering activity (alerts, transactions)', 'Risk Index score'),
    ),
    Connector(
        'Chainalysis',
        'Crypto AML & Blockchain Analytics',
        'Industry-leading blockchain analytics for VASP TM. Connector to pull KYT scores when wallet addresses are provided.',
        'https://www.chainalysis.com',
        status='Roadmap Q3 2026',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence', 'Supporting documents'),
    ),
    Connector(
        'TRM Labs',
        'Crypto AML & Blockchain Analytics',
        'Blockchain intelligence for compliance and law-enforcement use.',
        'https://www.trmlabs.com',
        status='Roadmap Q3 2026',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence'),
    ),
    Connector(
        'Elliptic',
        'Crypto AML & Blockchain Analytics',
        'Blockchain analytics with strong sanctions and exchange-risk data.',
        'https://www.elliptic.co',
        status='Roadmap Q3 2026',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Counterparty intelligence'),
    ),
    Connector(
        'Hummingbird',
        'Risk Orchestration',
        'Compliance workflow with case-management primitives. Bidirectional connector to post draft narratives back into cases.',
        'https://www.hummingbird.co',
        status='Roadmap Q4 2026',
        integration_type='REST API (bidirectional)',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Quantexa',
        'Enterprise FRAML & Decisioning Platforms',
        'Entity-resolution and network analytics; deployed at HSBC, Standard Chartered, and major banks.',
        'https://www.quantexa.com',
        status='Roadmap Q4 2026',
        integration_type='REST API',
        populates=('Counterparty intelligence', 'Subject (KYC, customer profile)'),
    ),
    Connector(
        'Lucinity',
        'Enterprise FRAML & Decisioning Platforms',
        'AI-native AML platform with explainability focus.',
        'https://www.lucinity.com',
        status='Roadmap Q4 2026',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)',),
    ),
    Connector(
        'Onfido (Entrust)',
        'Identity, eKYC, KYB & Onboarding',
        'Biometric and document-based KYC; acquired by Entrust 2024.',
        'https://onfido.com',
        status='Roadmap Q4 2026',
        integration_type='Webhook + REST',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Persona',
        'Identity, eKYC, KYB & Onboarding',
        'Configurable identity platform popular with US fintech.',
        'https://withpersona.com',
        status='Roadmap Q4 2026',
        integration_type='Webhook + REST',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Alloy',
        'Risk Orchestration',
        'Identity decision platform orchestrating multiple KYC vendors.',
        'https://www.alloy.com',
        status='Roadmap Q4 2026',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)',),
    ),
    Connector(
        'Refinitiv World-Check (LSEG)',
        'AML Data, Screening & Regulatory Intelligence',
        'Industry-standard global PEP and sanctions data. Enterprise-tier replacement for OpenSanctions.',
        'https://www.lseg.com/en/risk-intelligence/screening-and-monitoring',
        status='Roadmap Q4 2026',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Dow Jones Risk & Compliance',
        'AML Data, Screening & Regulatory Intelligence',
        'Curated risk and compliance data; enterprise-grade.',
        'https://www.dowjones.com/professional/risk/',
        status='Roadmap Q4 2026',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Snowflake',
        'Enterprise FRAML & Decisioning Platforms',
        'Pull customer / transaction / KYC data directly from a Snowflake warehouse to pre-fill case forms.',
        'https://www.snowflake.com',
        status='Roadmap Q4 2026',
        integration_type='JDBC / REST',
        populates=('Subject (KYC, customer profile)', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Databricks',
        'Enterprise FRAML & Decisioning Platforms',
        'Pull data from a Databricks lakehouse for STR drafting and feature derivation.',
        'https://www.databricks.com',
        status='Roadmap Q4 2026',
        integration_type='JDBC / REST',
        populates=('Subject (KYC, customer profile)', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Actico',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.actico.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Acuant (GBG Group)',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.acuant.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Advance.AI',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.advance.ai',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'AML Watcher',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.amlwatcher.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'AnChain.ai',
        'Crypto AML & Blockchain Analytics',
        'Crypto AML & Blockchain Analytics platform.',
        'https://www.anchain.ai',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence'),
    ),
    Connector(
        'Appian',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.appian.com/solutions/financial-services/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Arkose Labs',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.arkoselabs.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'AU10TIX',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.au10tix.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Authenteq',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.authenteq.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Aware',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://www.aware.com',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Azentio',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.azentio.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Babel Street',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://babelstreet.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'BehavioSec',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.behaviosec.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Berbix',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.berbix.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Beyond Identity',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.beyondidentity.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'BioCatch',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.biocatch.com/',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Black Kite',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://blackkite.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Callsign',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.callsign.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Castle.io',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://castle.io',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'CipherTrace',
        'Crypto AML & Blockchain Analytics',
        'Crypto AML & Blockchain Analytics platform.',
        'https://ciphertrace.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence'),
    ),
    Connector(
        'Clari5',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.clari5.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Cognitive View',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.cognitiveview.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Comarch',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.comarch.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Compliance Link',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.compliancelink.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'ComplyCube',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.complycube.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'CredoLab',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.credolab.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Daon',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.daon.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Darwinium',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.darwinium.com/',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'DataVisor',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.datavisor.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Deduce',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.deduce.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Delta Capita',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.deltacapita.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Eastnets',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.eastnets.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Effectiv.ai',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.effectiv.ai',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Emailage (LexisNexis)',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://risk.lexisnexis.com/products/emailage',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Encompass',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.encompasscorporation.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Facephi',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://facephi.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Featurespace',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.featurespace.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Feedzai',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://feedzai.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Fenergo',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.fenergo.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'FICO',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.fico.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Fincom.co',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.fincom.co',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Fingerprint',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://fingerprint.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Fircosoft',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://risk.lexisnexis.com/global/en/solutions/fircosoft',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'FiVerity',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.fiverity.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Flagright',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.flagright.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Forter',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.forter.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'FrankieOne',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.frankieone.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Fraud.net',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.fraud.net',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Fraugster',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.fraugster.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'FRISS',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.friss.com/',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'GBG',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.gbgplc.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Highnote',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://highnote.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'HooYu',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.hooyu.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'HUMAN Security',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.humansecurity.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'IBM',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.ibm.com/products/financial-crimes-insights',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'ID R&D',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.idrnd.ai',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'IDnow',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.idnow.io/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'IMTF',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.imtfglobal.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Incode',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.incode.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Incognia',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.incognia.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Innovalor – ReadID',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.readid.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Inscribe.ai',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.inscribe.ai',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'iProov',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.iproov.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Jumio',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.jumio.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Kasada',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.kasada.io',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Kharon',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.kharon.com/',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Kount',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://kount.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'LexisNexis Risk Solutions',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://risk.lexisnexis.com/',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Linkurious',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://linkurious.com',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Lithic',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://lithic.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'LSEG – Risk Intelligence',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://riskintelligence.lseg.com/',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Maltego',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.maltego.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Memcyco',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.memcyco.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Merkle Science',
        'Crypto AML & Blockchain Analytics',
        'Crypto AML & Blockchain Analytics platform.',
        'https://www.merklescience.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence'),
    ),
    Connector(
        'Minerva AI',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.minervaai.io',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Mitek Systems',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.miteksystems.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        "Moody's Analytics",
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.moodysanalytics.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Muinmos',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.muinmos.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'NameScan',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.namescan.io/',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Napier',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.napier.ai/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'NetGuardians',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.netguardians.ch/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Nethone',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://nethone.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'NeuroID',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.neuro-id.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'NICE Actimize',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.niceactimize.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'NOTO360',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.noto.ai/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'OCR Labs',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.ocrlabs.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Ondato',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.ondato.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Oracle',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.oracle.com/financial-crime-compliance/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Palantir',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://www.palantir.com',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Pindrop',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.pindrop.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Prove',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.prove.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Quantifind',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.quantifind.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Ravelin',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.ravelin.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Reality Defender',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://realitydefender.com',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Refine Intelligence',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.refineintel.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Regula',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.regulaforensics.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Ripjar',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.ripjar.com/',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Riskified',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.riskified.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'RiskNarrative',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.risknarrative.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Salviol',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.salviol.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'SAS',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.sas.com/en_us/industry/banking/fraud-financial-crime.html',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Sayari',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://sayari.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'SecuredTouch',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://securedtouch.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Sensity AI',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://sensity.ai',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'SentiLink',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.sentilink.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Seon',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://seon.io/',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Shufti Pro',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.shuftipro.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Sift',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.sift.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Signzy',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.signzy.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Silent Eight',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.silenteight.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Socure',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.socure.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Solidus Labs',
        'Crypto AML & Blockchain Analytics',
        'Crypto AML & Blockchain Analytics platform.',
        'https://www.soliduslabs.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Counterparty intelligence'),
    ),
    Connector(
        'SpecTrust',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.spectrust.com',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Strivacity',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.strivacity.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'SymphonyAI',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.symphonyai.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Taktile',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.taktile.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Tesselate',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.tesselate.net',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'ThetaRay',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.thetaray.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Tookitaki',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.tookitaki.com/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Traceable AI',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.traceable.ai',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Truepic',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://www.truepic.com',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Trulioo',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.trulioo.com/',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Trust Stamp',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://truststamp.ai',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'TypingDNA',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.typingdna.com',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'Veridas',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.veridas.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Veriff',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.veriff.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Vesta',
        'Behavioral & Device Intelligence',
        'Behavioral & Device Intelligence platform.',
        'https://www.vesta.io',
        status='On request',
        integration_type='REST API',
        populates=('Risk Index score', 'Triggering activity (alerts, transactions)'),
    ),
    Connector(
        'VIDA',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.vida.id',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Vouched',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.vouched.id',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Yoti',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.yoti.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'ZignSec',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.zignsec.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Zoloz',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.zoloz.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        'Cable',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://cable.tech',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Resistant AI',
        'Specialized Solutions',
        'Specialized Solutions platform.',
        'https://www.resistant.ai',
        status='On request',
        integration_type='REST API',
        populates=('Supporting documents',),
    ),
    Connector(
        'Salesforce Financial Services Cloud',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.salesforce.com/financial-services/',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Castellum.AI',
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.castellum.ai',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
    Connector(
        'Verafin (Nasdaq)',
        'Enterprise FRAML & Decisioning Platforms',
        'Enterprise FRAML & Decisioning Platforms platform.',
        'https://www.verafin.com',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'ACAMS Risk Assessment',
        'Risk Orchestration',
        'Risk Orchestration platform.',
        'https://www.acams.org',
        status='On request',
        integration_type='REST API',
        populates=('Triggering activity (alerts, transactions)', 'Case post-back'),
    ),
    Connector(
        'Trulioo (Enterprise)',
        'Identity, eKYC, KYB & Onboarding',
        'Identity, eKYC, KYB & Onboarding platform.',
        'https://www.trulioo.com',
        status='On request',
        integration_type='REST API',
        populates=('Subject (KYC, customer profile)', 'Supporting documents'),
    ),
    Connector(
        "Moody's BvD (Orbis / Compliance Catalyst)",
        'AML Data, Screening & Regulatory Intelligence',
        'AML Data, Screening & Regulatory Intelligence platform.',
        'https://www.moodys.com/web/en/us/capabilities/compliance.html',
        status='On request',
        integration_type='REST API',
        populates=('Sanctions / PEP screening', 'Adverse media findings'),
    ),
]


def by_category() -> dict[str, list[Connector]]:
    """Group connectors by category, in CATEGORIES display order."""
    grouped: dict[str, list[Connector]] = {c: [] for c in CATEGORIES}
    for c in CONNECTORS:
        grouped.setdefault(c.category, []).append(c)
    # Within each category, sort: Live first, then alphabetical
    for cat in grouped:
        grouped[cat].sort(key=lambda x: (STATUS_ORDER.get(x.status, 99), x.name.lower()))
    # Drop empty categories
    return {k: v for k, v in grouped.items() if v}


def by_status() -> dict[str, list[Connector]]:
    """Group connectors by status, ordered by STATUS_ORDER."""
    grouped: dict[str, list[Connector]] = {}
    for c in CONNECTORS:
        grouped.setdefault(c.status, []).append(c)
    ordered: dict[str, list[Connector]] = {}
    for status in sorted(grouped.keys(), key=lambda s: STATUS_ORDER.get(s, 99)):
        ordered[status] = sorted(grouped[status], key=lambda c: c.name.lower())
    return ordered


def search(query: str) -> list[Connector]:
    """Case-insensitive substring search on name + category + description."""
    q = (query or '').strip().lower()
    if not q:
        return []
    matches = []
    for c in CONNECTORS:
        haystack = (c.name + ' ' + c.category + ' ' + c.description).lower()
        if q in haystack:
            matches.append(c)
    matches.sort(key=lambda x: (STATUS_ORDER.get(x.status, 99), x.name.lower()))
    return matches
